[I] Connected!
[I] Response from FEC: {'res': 200, 'id': 1}
[!] Ending...
'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
Traceback (most recent call last):
  File "C:\Users\Usuario\Documents\UNI\2022 - 23 Q2\Work\Codes\7b659cf16faa821bdd80\client.py", line 164, in server_conn
    input('[*] Press enter to send a VNF...')
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python39\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
Thread ID 5292 does not exist!
Traceback (most recent call last):
  File "C:\Users\Usuario\Documents\UNI\2022 - 23 Q2\Work\Codes\7b659cf16faa821bdd80\client.py", line 261, in main
    time.sleep(1)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Usuario\Documents\UNI\2022 - 23 Q2\Work\Codes\7b659cf16faa821bdd80\client.py", line 230, in kill_thread
    raise ValueError("Thread ID " + str(thread_id) + " does not exist!")
ValueError: Thread ID 5292 does not exist!
